name: RPG
version: '${project.version}'
main: me.jqrtox.rpg.RPG
api-version: '1.20'
commands:
  collections:
    description: "Open Collection Menu"
    usage: "/collections"
  sell:
    description: "Open sell Gui"
    usage: "/sell"
